# Podstawowe informacje o projekcie
sonar.projectKey=roberts911_sast-thesis-testbed
sonar.organization=roberts911

# Wskazanie katalogu do analizy
sonar.sources=synthetic

# Opcjonalnie: wykluczenie plików, których nie chcemy skanować
sonar.exclusions=synthetic/ground_truth.csv

# Wymuszenie analizy dla konkretnego języka (zapobiega konfliktom)
sonar.language=js,ts